language: objective-c
os: osx
xcode_project: VelocidiSDK/VelocidiSDK.xcodeproj # path to your xcodeproj folder
xcode_scheme: VelocidiSDKTests
xcode_destination: platform=iOS Simulator,OS=11.4,name=iPhone X

after_success:
  - bash <(curl -s https://codecov.io/bash)
