language: objective-c
os: osx
xcode_workspace: VelocidiSDK.xcworkspace # path to your xcodeproj folder
xcode_scheme: VelocidiSDKTests

script:
  - set -o pipefail && xcodebuild -workspace VelocidiSDK.xcworkspace -scheme VelocidiSDK -sdk "iphonesimulator$TEST_SDK" -destination "platform=iOS Simulator,OS=${TEST_SDK},name=iPhone X" GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO clean build test | xcpretty --color 

before_install:
  - xcrun instruments -w "iPhone X (${TEST_SDK})" || sleep 15

after_success:
 - bash <(curl -s https://codecov.io/bash) -J 'VelocidiSDK'

jobs:
  include:
    # - env: 
        # - TEST_SDK=11.0
      # osx_image: xcode9
    # - env: 
        # - TEST_SDK=11.1
      # osx_image: xcode9.1
    # - env: 
        # - TEST_SDK=11.2
      # osx_image: xcode9.2
    # - env: 
        # - TEST_SDK=11.3
      # osx_image: xcode9.3
    # - env: 
        # - TEST_SDK=11.4
      # osx_image: xcode9.4.1
    - env: 
        - TEST_SDK=12.0
      osx_image: xcode10
    - env: 
        - TEST_SDK=12.1
      osx_image: xcode10.1
    - env: 
        - TEST_SDK=12.2
      osx_image: xcode10.2
    - name: Cocoapods Lint
      script: 
        - pod repo update
        - pod install
        - pod lib lint --verbose VelocidiSDK.podspec
      after_success: null
      before_install: null
    - name: README.md check
      script: 
        - cat docs/HEADER.md docs/BODY.md | diff README.md -
      after_failure:
        - echo "To update the README.md file at the root of the repository you\
         should update the files HEADER.md BODY.md in the docs folder and then\
         join them (e.g., `cat docs/HEADER.md docs/BODY.md > README.md`)."
      after_success: null
      before_install: null
notifications:
  email:
    recipients:
      - baco@velocidi.com
    on_success: never
    on_failure: change
