# Uncomment the next line to define a global platform for your project
platform :ios, '11.4'

target 'VelocidiSDK' do
  # Pods for VelocidiSDK
  # use_frameworks!

  target 'VelocidiSDKTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

