#import <Foundation/Foundation.h>
#import <VelocidiSDK/VelocidiSDK.h>
@class AFHTTPSessionManager;

NS_ASSUME_NONNULL_BEGIN

@interface VSDKUtil : NSObject

/**
  Helper method that generates a User-Agent string similar to the one generated by the AFNetworking 
  framework with the adition of containing an name of the VelodiciSDK framework and build number.
  Example: `AppName/AppVersion VelocidiSDK/2 (iPhone; iOS 11.0.1; Scale/3.00)`.
  @returns User-Agent string
 */
- (NSString *)getVersionedUserAgent;

/**
  Retrieve the advertisingIdentifier UUID.
  @returns advertisingIdentifier UUID.
 */
- (NSUUID *)getAdvertisingIdentifier;

/**
  Verify if tracking is allowed or if the user has opted-out of being tracked in this application.
  @returns True if tracking is allowed, false if otherwise.
 */
- (bool) isAdvertisingTrackingEnabled;

/**
  Modify an AFHTTPSessionManager to accept all types of responses.
 */
+ (void) setAcceptAllResponses: (AFHTTPSessionManager *) sessionManager;
@end

NS_ASSUME_NONNULL_END
