source 'https://cdn.cocoapods.org/'
platform :ios, '11.0'
workspace '../VelocidiSDK.xcworkspace'

use_frameworks!

target "SwiftExample" do
  project 'SwiftExample/SwiftExample.xcodeproj'

  pod 'VelocidiSDK', :path => '../'
  pod 'SwiftLint'
end

target "ObjcExample" do
  project 'ObjcExample/ObjcExample.xcodeproj'

  pod 'VelocidiSDK', :path => '../'
end
