source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
workspace '../VelocidiSDK.xcworkspace'

use_frameworks!

target "SwiftExample" do
  project 'SwiftExample/SwiftExample.xcodeproj'

  pod 'VelocidiSDK', :path => '../'
end

target "ObjcExample" do
  project 'ObjcExample/ObjcExample.xcodeproj'

  pod 'VelocidiSDK', :path => '../'
end
