name: iOS CI

on: [push]

jobs:
  test:
    name: "Build and test Velocidi SDK using [${{ matrix.os }}, xcode${{ matrix.xcode }}, sdk${{ matrix.sdk }}, ${{ matrix.device }}]"
    env:
      WORKSPACE: "VelocidiSDK.xcworkspace"
      SCHEME: "VelocidiSDK"
    strategy:
      matrix:
        include:
         - os: "macos-10.15"
           xcode: "10.3"
           sdk: "12.4"
           device: "iPhone X"
         - os: "macos-10.15"
           xcode: "11.7.0"
           sdk: "13.7"
           device: "iPhone 11"
         - os: "macos-10.15"
           xcode: "12.4"
           sdk: "14.4"
           device: "iPhone 11 Pro Max"
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v1
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "${{ matrix.xcode }}"
      - name: "Install Dependencies"
        run: make install
      - name: "Compile and Test Velocidi SDK"
        env:
          TEST_SDK: "${{ matrix.sdk }}"
          TEST_DEVICE: "${{ matrix.device }}"
        run: |
          make
          make test
      - name: "Verify code linting generated no changes"
        run: git diff --exit-code

  build-example-applications:
    name: "Build example applications"
    needs: test
    runs-on: "macos-latest"
    steps:
      - uses: actions/checkout@v1
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "latest-stable"
      - name: "Install Dependencies"
        run: make install
      - name: "Build example Objective-C application"
        run: make build-objc-example
      - name: "Build example Swift application"
        run: make build-swift-example
      - name: "Verify code linting generated no changes"
        run: git diff --exit-code

  pods-lint:
    name: "Cocoapods Lint"
    needs: test
    runs-on: "macos-latest"
    steps:
      - uses: actions/checkout@v1
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "latest-stable"
      - name: "Lint"
        run: |
          pod repo update
          make install
          make podlint
